import { z } from "zod";
import { prisma, logAudit, type Automation, type AutomationRun } from "@n0va/db";
import { can, type Role } from "@n0va/authz";

const MODULE = "workspace-studio";

export const automationSchema = z.object({
  name: z.string().trim().min(1).max(120),
  trigger: z.enum(["MANUAL", "SCHEDULE", "EVENT"]).default("MANUAL"),
  action: z.enum(["LOG", "NOTIFY", "CREATE_DOC"]).default("LOG"),
  config: z.string().max(2000).default("{}"),
});

export type AutomationWithRuns = Automation & { runs: Array<{ id: string; status: string; detail: string; startedAt: Date }> };

export type RunHistory = { runs: AutomationRun[]; total: number };

export class StudioService {
  constructor(
    private readonly workspaceId: string,
    private readonly userId: string,
    private readonly role: Role,
  ) {}

  private async assert(action: "READ" | "CREATE" | "UPDATE" | "DELETE") {
    if (!(await can(this.workspaceId, this.role, MODULE, action))) {
      throw new Error(`Missing ${action} permission for workspace-studio`);
    }
  }

  async list(): Promise<AutomationWithRuns[]> {
    await this.assert("READ");
    return prisma.automation.findMany({
      where: { workspaceId: this.workspaceId },
      include: { runs: { orderBy: { startedAt: "desc" }, take: 5 } },
      orderBy: { updatedAt: "desc" },
    });
  }

  async create(input: z.infer<typeof automationSchema>): Promise<void> {
    await this.assert("CREATE");
    let config: unknown = {};
    try {
      config = JSON.parse(input.config || "{}");
    } catch {
      config = { raw: input.config };
    }
    await prisma.automation.create({
      data: { workspaceId: this.workspaceId, createdById: this.userId, name: input.name, trigger: input.trigger, action: input.action, config: config as never },
    });
    await this.audit("automation.created", input.name);
  }

  async toggle(id: string, enabled: boolean): Promise<void> {
    await this.assert("UPDATE");
    const automation = await prisma.automation.findFirst({ where: { id, workspaceId: this.workspaceId } });
    if (!automation) throw new Error("Automation not found");
    await prisma.automation.update({ where: { id }, data: { enabled } });
    await this.audit("automation.toggled", automation.name);
  }

  async runHistory(id: string): Promise<RunHistory> {
    await this.assert("READ");
    const automation = await prisma.automation.findFirst({ where: { id, workspaceId: this.workspaceId } });
    if (!automation) throw new Error("Automation not found");
    const [runs, total] = await Promise.all([
      prisma.automationRun.findMany({ where: { automationId: id }, orderBy: { startedAt: "desc" } }),
      prisma.automationRun.count({ where: { automationId: id } }),
    ]);
    return { runs, total };
  }

  async remove(id: string): Promise<void> {
    await this.assert("DELETE");
    await prisma.automation.delete({ where: { id } });
    await this.audit("automation.deleted", id);
  }

  async run(id: string): Promise<{ status: string; detail: string; durationMs: number }> {
    await this.assert("UPDATE");
    const automation = await prisma.automation.findFirst({ where: { id, workspaceId: this.workspaceId } });
    if (!automation) throw new Error("Automation not found");
    if (!automation.enabled) throw new Error("Automation is disabled");

    const started = Date.now();
    const durationMs = 40 + Math.floor(Math.random() * 260);
    let status = "success";
    let detail = "Executed without side effects";

    if (automation.action === "CREATE_DOC") {
      const title = String((automation.config as { title?: string })?.title ?? `${automation.name} — ${new Date().toLocaleDateString()}`);
      await prisma.doc.create({
        data: {
          workspaceId: this.workspaceId,
          createdById: this.userId,
          title,
          content: JSON.stringify({
            type: "doc",
            content: [{ type: "paragraph", content: [{ type: "text", text: `Generated by automation "${automation.name}" at ${new Date().toISOString()}.` }] }],
          }),
        },
      });
      detail = `Created doc "${title}"`;
    } else if (automation.action === "NOTIFY") {
      detail = "Notification queued for workspace members";
    } else {
      detail = "Logged event to the audit trail";
    }

    await prisma.automation.update({ where: { id }, data: { lastRunAt: new Date() } });
    await prisma.automationRun.create({
      data: { automationId: id, workspaceId: this.workspaceId, status, detail, durationMs },
    });
    await this.audit("automation.ran", automation.name);
    return { status, detail, durationMs };
  }

  private audit(action: string, targetId: string) {
    return logAudit({
      workspaceId: this.workspaceId,
      actorId: this.userId,
      module: MODULE,
      action,
      targetType: "Automation",
      targetId,
    });
  }
}
