export { MailService, type MailFolder, type MailUnreadCounts, type MailStatus, type MailThreadView, type AiSuggestion } from "./server";
export { MailApp, type MailThread } from "./components";
export { MailEngine, getMailEngine, type MailEngineConfig, type SendMailInput, type MailStats } from "./engine";
export { parseSearchQuery, executeSearch, getSearchSuggestions, type SearchQuery, type SearchResult, type SearchOptions } from "./search";
export { EDiscoveryEngine, type LegalHold, type RetentionPolicy, type DiscoveryFilters, type LegalHoldScope } from "./ediscovery";
export { getMailAgentTools, mailAgentWorkflows, AGENT_PERSONAS, type AgentPersona, type MailAgentTool, type AgentContext, type AgentWorkflow } from "./n0va1o-agent";
export { VisualRulesBuilder, AgentPanel, AdvancedSearchBar, SecurityDashboard, VoiceNoteRecorder, type RuleCondition, type RuleGroup, type AgentPersona as AgentPersonaUI, type SecurityEvent } from "./components-enhanced";
export { EmailAccountSetup } from "./account-setup";
export { SmtpTransport, ImapReceiver, EmailAccountManager, createSmtpTransport, createImapReceiver, getEmailAccountManager, type SmtpConfig, type ImapConfig, type SendEmailInput, type SendEmailResult, type InboundEmail, type EmailAccount } from "./transport";
export { SecurityPipeline, SpfEvaluator, DkimEngine, DmarcEvaluator, AntiSpamClassifier, AntivirusEngine, ContentSanitizer, ReputationEngine } from "./security";
export { AiEngine, ThreadSummarizer, SmartReplyEngine, PhishingDetector, SemanticSearchEngine, ContentAnalyzer } from "./ai";
