export { AniService } from "./server";
export { AniChat } from "./components";
export type { AniActions } from "./components";
export { N0VA_ANI, createANI, classifyIntent, createWorkspaceContext, buildWorkspaceContext } from "./engine";
export type { ANIConfig, ANIResponse, ANISnapshot, WorkspaceContext, UserIntent, ConsciousnessState, IntentClass, InterfaceMode, ConsciousnessTier } from "./engine";
export { ConsciousnessStack, PerceptualAwareness, WorkingMemory, LongTermMemory, Metacognition, ConsciousnessIntegration } from "./consciousness";
export type { ConsciousnessMetrics, ConsciousnessThresholds, PerceptualSignal, WorkingMemoryItem, LongTermMemoryEntry } from "./consciousness";
export { PentAudienceManager, ExternalInterface, InternalInterface, AutonomousInterface, NeuralInterface, AmbientInterface } from "./interfaces";
export type { PentAudienceState, ExternalInterfaceConfig, InternalInterfaceConfig, AutonomousInterfaceConfig, NeuralInterfaceConfig, AmbientInterfaceConfig } from "./interfaces";
export { callLlm, callOpenaiLike, callAnthropic, callGemini, DEFAULT_SYSTEM_PROMPT, composeFallbackReply, getTypingDelay } from "./providers";
export type { LlmCallResult, ToolCallRequest, ToolExecutionResult } from "./providers";
export { retrieveRagContext, buildRagPrompt, rankRagResults } from "./rag";
export type { RagContext, RagDocument } from "./rag";
export { PersistentMemorySystem, createMemorySystem } from "./memory";
export type { MemoryEntry, MemoryStats, ConsolidationResult, RetrievalQuery, RetrievalResult } from "./memory";
export { XAIFramework, createXAI } from "./xai";
export type { ExplanationRequest, ExplanationResult, CitationDetail } from "./xai";
export { AdaptiveLearningEngine, createAdaptiveEngine } from "./adaptive";
export type { UserProfile, CommunicationStyle, DecisionPreferences, CognitiveProfile, TemporalPatterns, FeedbackEntry, AdaptationResult } from "./adaptive";
export { CrisisResilienceEngine, createCrisisEngine } from "./resilience";
export type { FailureSeverity, FailureEvent, CircuitBreakerState, CrisisPlaybook } from "./resilience";
export { KnowledgeGraphEngine, createKnowledgeGraph } from "./knowledge-graph";
export type { KnowledgeEntity, Relationship, GraphPath, GraphQueryResult } from "./knowledge-graph";
export { PredictiveIntelligenceEngine, createPredictiveEngine } from "./predictive";
export type { ProactiveTrigger, BehavioralPrediction, AnomalyPrediction } from "./predictive";
export { DEFAULT_ANI_SETTINGS } from "./types";
export type { AniSettings, ToolCallRecord, Sensitivity, MemoryTier } from "./types";
export { TwinManager } from "./twins";
export type { DigitalTwin, TwinType, TwinSimulation } from "./twins";
export { CausalReasoningEngine } from "./causal";
export type { CausalNode, CausalEdge, CounterfactualResult, CausalLevel } from "./causal";
export { HyperdimensionalComputer } from "./hyperdimensional";
export type { HyperVector, HDC_DIMENSION } from "./hyperdimensional";
export { MultiAgentSwarmOrchestrator, createSwarmOrchestrator } from "./swarm";
export type { AgentRole, AgentTask, SwarmPlan, SwarmResult } from "./swarm";
export { hydrateContext, formatContextForPrompt } from "./context-hydration";
export type { ContextDimensions, HydratedContext } from "./context-hydration";
export { evaluateHITL, createHITLChecker } from "./hitl";
export type { HITLLevel, HITLCheck, ActionContext } from "./hitl";
